# 生成器
## 1. 生成器基础
生成器是ES6中新增的一个及其灵活的结构。可以说它是一种"函数"，因为它以函数的形式出现，即在函数名称前加一个 **\***。最主要的还是因为它能够在函数块内进行 **暂停** 和 **恢复执行** 的操作，所以十分强大。  
调用生成器函数会生成一个 **生成器对象** ， 生成器对象 **一开始会处于暂停的状态** 。与迭代器相似，生成器对象也实现了 **Iterator** 接口，因此具有next()方法。调用next()可以让生成器 **开始或恢复执行** 。如：
```JavaScript
// 定义生成器，ps:()=>{}箭头函数不能用于定义生成器
function *getName(){
    console.log('douchen');
}
let name = getName();
// 生成器函数只会在初次调用next()后开始执行。
name.next(); // douchen
console.log(name.next()) // { value: undefined, done: true }，因为初始就没设置数值，所以迭代已耗尽。
```
## 2. yield关键字
生成器中最有用的莫过于 **yield** ，它可以让生成器停止和开始执行。生成器函数在 **遇到yield关键字之前，都会正常执行** 。 **遇到之后则会停止执行，函数作用域的状态也会被保留** 。如果我们想 **继续执行** 该怎么办呢？想迭代器一样 **调用next()** 方法即可。
```JavaScript
// 创建生成器函数
function *Count(){
    console.log('first:');
    yield 'douchen';
    console.log('second:');
    yield 'aoteman';
    return 'end';
}
let count = Count();
// 生成器函数需要用next()启动
console.log(count.next()); 
// first: 
// { value: 'douchen', done: false }
console.log(count.next()); 
// second: 
// { value: 'aoteman', done: false }
console.log(count.next());
// { value: 'end', done: true }
```
### 生成器对象作为可迭代对象
生成器具有这么强大的功能，那么如何使用呢？如果 **把生成器对象作为可迭代对象** ，那是多么的方便啊！~我们甚至可以用 **自定义生成器替代数组** ，生成我们需要的数据。如：
```JavaScript
// 创建一个0~100间所有偶数的数组
const myArr = Array.from({
    [Symbol.iterator]: function*(){
        for(let i = 0; i <= 100; i++){
            if(i % 2 === 0){
                yield i 
            }
        } 
    }
})
console.log(myArr); // 0 2 4 ... 100
```
上面这块代码是固定的，可以理解为没有参数的函数，无法重复利用。每次需求更改就需要在for里面修改start, end和step，很"笨拙"。  
我们可以更加" **聪明** "一点，直接实现一个范围偶数数组生成器，能够 **像带参数的函数一样重复利用**。如：
```JavaScript
// 创建一个范围偶数数组生成器
const rangeArr = (start, end, step) => {
    function *iter(){ // 构建生成器
        for(let i = start; i <= end; i += step){
            if(i % 2 === 0){ // 符合要求的就通过yield实现 " 添加 "
                yield i 
            }
        } 
    }
    return{
        [Symbol.iterator]: iter
    }
}
console.log(Array.from(rangeArr(50, 100, 2))); // 50 52 54 ... 100
```
### yield* 产生可迭代对象的子项
使用 **\*** 可以增强yield的行为，让它能够迭代一个可迭代对象，从而一次产生一个值。如：
```JavaScript
function* generatorFn(){
    yield* [1, 2, 3];
}
let generatorObject = generatorFn();
for(const x of generatorObject){
    console.log(x); // 1 2 3
}
// generatorFn()等价于
function* generatorFn2(){
    for(const x of [1, 2, 3]){
        yield x;
    }
}
```
简单地来说，实际上 **yield\*** 只是将一个 **可迭代对象** 序列化为 **一连串可以单独产生的值** 。
### yield* 实现递归
**yield\*** 最有用的地方就是实现 **递归** 操作，此时生成器可以 **产生自身** 。如：
```JavaScript
function *nTimes(n){
    if( n < 5 ){
        yield n * (n + 1);
        yield* nTimes(n + 1)
    }
}
for(const x of nTimes(0)){
    console.log(x); // 0=0x1 2=1x2 6=2x3 12=3x4 20=4x5
}
```
既然使用yield\*可以方便地表达递归算法，而 **图结构** 非常适合递归遍历，因此可以用 **yield\*对图进行递归遍历** ，测试该 **图是否连通** 。下面是用yield\*实现图的 **深度遍历**，十分简单：只需要 **从一个结点开始，递归遍历每个结点的邻居结点** ，如果 **没有被访问过** 则加入visited数组中保存。最后 **如果visited数组中包含了所有结点，则说明该图是连通** 的。如下所示：
```JavaScript
// 创建结点Node类
class Node {
    constructor(id) {
        this.id = id;
        this.neighbors = new Set();
    }
    // 结点双向连接
    connect(node) {
        if (node !== this) {
            this.neighbors.add(node);
            node.neighbors.add(this);
        }
    }
}

// 创建随机双向图类
class graph {
    constructor(size) {
        this.nodes = new Set();
        for (let i = 0; i < size; i++) {
            this.nodes.add(new Node(i));
        }
        const threshold = 1 / size; // 概率阈值，是否连接
        for (const x of this.nodes) {
            for (const y of this.nodes) {
                if (Math.random() < threshold) {
                    x.connect(y);
                }
            }
        }
    }
    print() { // 输出随机图
        for (const node of this.nodes) {
            const ids = [...node.neighbors].map((node) => node.id).join(',');
            console.log(node.id.toString() + ':' + ids);
        }
    }
    isConnect(){ // 判断随机图是否连通，即每两个点都可达
        const visitedNodes = new Set();
        function* traverse(nodes){ // 使用递归生成器
            for(const node of nodes){
                if(!visitedNodes.has(node)){
                    yield node; // 遇到yield，暂停函数并保存函数当前状态，可利用.next()或for of继续执行。
                    yield* traverse(node.neighbors);
                }
            }
        }
        const firstNode = this.nodes[Symbol.iterator]().next().value;
        for(const node of traverse([firstNode])){ 
            // 继续开始执行traverse函数，并将node添加入visitedNodes
            visitedNodes.add(node);
        };
        if(visitedNodes.size === this.nodes.size){
            return true
        }else{
            console.log(visitedNodes)
            return false
        }
    }
}

const g = new graph(6);
g.print();
g.isConnect();
```
## 3. 提前终止生成器
与迭代器类似，生成器也支持 **可关闭** 的概念。一个实现Iterator接口的对象一定有 **next()** 方法，还有一个可选的 **return()** 方法用于提前终止迭代器。生成器对象除了有这两种方法，还有第三个方法： **throw()** 。  
**return()** 和 **throw()** 都可以强制生成器进入关闭状态。
> **return()**
>> return()方法会强制生成器进入关闭状态。提供给return()方法的值，就是 ***终止迭代器对象的值*** 。如：
>> ```JavaScript
>> function* generatorFn(){
>>    yield* [1, 2, 3];
>> }
>> let g = generatorFn();
>> console.log(g); // Object [Generator] {<suspended>}
>> console.log(g.return(4)); // { value: 4, done: true }
>> console.log(g); // Object [Generator] {<closed>}
>> ```
>> 生成器只要进入关闭状态，后续调用next()会显示 ***done: true*** 状态，而提供的任何返回值都 ***不会被存储或传播*** 。如：
>> ```JavaScript
>> console.log(g.next()); // { value: undefined, done: true }
>> ```
>> for - of 循环等 ***内置迭代器的结构*** 会忽略状态为 ***done: true的IteratorObject*** 内部返回的值。如：
>> ```JavaScript
>> let g = generatorFn();
>> for(const x of g){
>>   if(x > 1){
>>     g.return(4);
>>   }
>>   console.log(x); // 1 2, 因为在x=2的时候关闭了生成器g, for of 无法继续到生成器 g 中的后续值。因此后续不会输出状态为 done: true的对象值。
>> }
>> ```

> **throw()**
>> throw()方法的原理是： ***在暂停的时候将一个提供的错误注入到生成器对象中。如果错误未被处理，生成器就会关闭*** 。如：
>> ```JavaScript
>> // 任以上述的generatorFn()为例
>> const g = generatorFn();
>> console.log(g); // Object [Generator] {<suspended>}
>> try{
>>     g.throw('error'); // 抛出一个字符串"error"错误。
>> }catch(e){
>>     console.log(e); // error
>> }
>> console.log(g); // Object [Generator] {<closed>}, 没有处理错误，因此生成器会关闭。
>> ```
>> 但是，如果生成器函数 ***内部*** 处理了这个错误，那么生成器就不会关闭，还可以恢复执行。错误处理会跳过对应的yield。如：
>> ```JavaScript
>> function* generatorFn(){
>>     for(const x of [1, 2, 3]){
>>         try{
>>             yield x;
>>         }catch(e) {} // 捕获错误并处理。
>>     }
>> };
>> const g = generatorFn();
>> console.log(g.next()); // { value: 1, done: false }
>> g.throw('error'); // 抛出一个错误：字符串"error"
>> console.log(g.next()); // { value: 3, done: false }
>> ```
>> 生成器在 ***try/catch*** 块中的yield关键字处会暂停执行。在暂停期间，throw()方法向生成器对象中注入了一个错误：字符串"error"。这个错误会被
yield关键字抛出。因为 ***错误使在生成器的try/catch块中抛出的*** ，所以仍然在生成器内部被捕获。然而，由于yield抛出了错误，***生成器就不会再产出值2*** 。此时，生成器函数继续执行，在下一次迭代再次遇到yield关键字时产出了值 ***3***。
